### ISSUE TITLE
[Meta] Port to Qt6

### ISSUE THREAD

**Issue by ayalhw** [Project-LemonLime/Project_LemonLime#93]
Steps:
- [x] add Qt6 support (https://github.com/Project-LemonLime/Project_LemonLime/pull/71) (https://github.com/Project-LemonLime/Project_LemonLime/commit/770e2f43b3304e76056993fd157e85cc32d50391) (https://github.com/Project-LemonLime/Project_LemonLime/commit/b1203f2f93b0c6ad6d1d5264b0d72339f869b8fd) (https://github.com/Project-LemonLime/Project_LemonLime/commit/1d173fadb76f131545a18ca0f00d5d45a1df7d47) (https://github.com/Project-LemonLime/Project_LemonLime/commit/ea64e3a0327ef421b13589db10238ed817d1dcfc) (https://github.com/Project-LemonLime/Project_LemonLime/commit/81e31e84b88b9b2b5969fe85e75f1dadd47b240a) (https://github.com/Project-LemonLime/Project_LemonLime/commit/f3d0bc95c24826dbb9fad0b819a0b0d495704007)
- [ ] add Qt6 test CI
- [ ] add Qt6 release build
- [ ] default Qt6

**Comment by alphagocc** [comment]
Contest can‘t be saved properly on Qt6
Contest created by Project_Lemon can't be read
